### ISSUE TITLE
Compatibilty with Arduin Nano ESP32?

### ISSUE THREAD

**Issue by Yankoboy** [KKest/ESP-rplidarS2#3]
Is Arduino ESP32 board compatible with the presented code?

I connected the RPLidar S2 Rx to Tx (D0) of Arduino board, TX tot the RX (D1) of the Arduino board. RPLidar S2 Power from external power supply, Arduino power from USB port. Common grounds. Installing the library in Arduino IDE 2.x went OK. Uploading the expres_scan.ino to Arduino Nano ESP32 went OK (only after upgrade In Arduino IDE of the Arduino_ESP32 board to version 2.0.12). RPLidar is active ( power take up 0.34 A) .
But, the serial monitor displays  only "0.00 deg |    0 mm". After some 10-15 seconds there migth be some activity noted in the first line of the Serial Monitor, but no data.
I changed in the sketch Serial2 tot Serial0, Serial1 without results.

Is this a case of pin-confusion at the ArduinoESP32? How to resolve?

**Comment by KKest** [comment]
Yes it should be compatible.

D0 and D1 (Serial0) should be the same UART that is used to commuicate with your PC. There is a second UART at D8 and D9 [nano-esp32/cheat-sheet](https://docs.arduino.cc/tutorials/nano-esp32/cheat-sheet). Try that one. 
Does the Lidar start spinning after the call of  `lidar.start(express)`?
Did you set the right Baudrate at the Serial Monitor?

**Comment by aghasaadmohammad** [comment]
Does it work with
AZDelivery ESP32 NodeMCU Module WLAN WiFi Dev Kit C Development Board with CP2102 ? anyone tested?

**Comment by Yankoboy** [comment]
Hi Kkest, I rebuild a stable set-up Arduino Nano ESP, RPLidarS2 and power supply (for the lidar) in stead of ealier bread board set up. As before common ground for lidar and arduino.  I tried the serial connections (Rx to Tx, Tx to Rx) at D0/D1 and the suggested D8/D9 as the Serial2 (Rx to Tx, Tx to Rx) but also  as Serial0 and as Serial1 in the sketch. Baudrate for Serial monitor is the required 115200. Unfortunately all without succes. The lidar does not spin. The serial monitor only shows empty list "0.00 deg | 0 mm". Reconnecting the RPLidar S2 to the Win10 PC (Slamtec Serial/USB converter and USB power supply ) and using the offline Slamtec Robostudio show RPLidar S2 working correctly,, with the characteristic sound of the spinning lidar. Any idea of what goes wrong here? IS this Arduino NanoESP32 related? I can assist by fast testing after changes to the library software. Ik look forward to your reply.

**Comment by KKest** [comment]
@aghasaadmohammad I worked with an AZDelivery ESP32 NodeMCU Module WLAN WiFi Dev Kit C Development Board with CP2102  when I wrote this code. Use the Serial2 at Pins GPIO 16 & 17


@Yankoboy The Lidar should start turning after calling <lidar.start(express)>. It seems that the connection is not correct. Try to get the status out of the lidar with the function before and after `lidar.start(express)`.

`
stDeviceStatus_t status=getDeviceHealth()
Serial.println(status. status);
Serial.println(status.errorCode_high<<8|status.errorCode_low);
`

**Comment by aghasaadmohammad** [comment]
> @aghasaadmohammad I worked with an AZDelivery ESP32 NodeMCU Module WLAN WiFi Dev Kit C Development Board with CP2102  when I wrote this code. Use the Serial2 at Pins GPIO 16 & 17
> 
> @Yankoboy The Lidar should start turning after calling <lidar.start(express)>. It seems that the connection is not correct. Try to get the status out of the lidar with the function before and after `lidar.start(express)`.
> 
> `stDeviceStatus_t status=getDeviceHealth() Serial.println(status. status); Serial.println(status.errorCode_high<<8|status.errorCode_low);`

I am really happy that its working, thankyou @KKest , The only thing which i wonder is for some period of time it shows 0 deg 0 mm then after 2 seconds almost it shows data and goes in loop. Do you know the problem?
Really thankyou for this repo and your help.

**Comment by Yankoboy** [comment]
Hello, here are my observations using the library, this time on a NodeMCU-ESP32-JoyIT. 

 

Connected to GPIO1&17 (TX2/RX2) the lidar works fine , starting up OK after a reset and showing the data for view field 5-175 degree.

But after some 3 minutes there was a sudden stop and no more data coming. Rotation has stopped. Power supply still OK.

I did a reset on the board an lidar started again but only for a minute or so. After that I couldn’t get the lidar started any more. 

I checked all connection and also rebuild everything without  success.

I checked back the good operation of  the RPLidar S2 with Robostudio (Win10) and device works  OK.

 

Any ideas what  happens here?

Thanks  a lot for your appreciated assistance!

(PS : I have not done yet the lidar healthstatus check for the Arduino Nano ESP32)

 

KKest : Edit because of mail leftover

**Comment by KKest** [comment]
@Yankoboy 
I had similar issues. I hooked up the Lidar through a breadboard and jumper wires when I started to test the lidar.
The connection was not stable. So the Lidar stopped turning after a short time. I ordered conntectors and soldered everything together. The Lidar worked then without issues.
