### ISSUE TITLE
Standard Mode not working

### ISSUE THREAD

**Issue by jakobofner** [KKest/ESP-rplidarS2#4]
Hi,

is there also a test-program for the standard mode available. I do not get it running when I change the mode to standard in the example program:
`#include "rpLidar.h"
  #include "rpLidarTypes.h"
  
  rpLidar lidar(&Serial2,1000000);
  
  
  void setup() {
    Serial.begin(115200);
    lidar.resetDevice(); //reset the device to be sure that the status is good
    lidar.setAngleOfInterest(5,175); //Set the field of view that is saved to Data
    lidar.start(standard); //start the express scan of the lidar
  }
  
  void loop()
  {
    lidar.readMeasurePoints();// reads a full scan and save it to Data
    for(int i=0;i<sizeof(lidar.Data)/sizeof(point_t);i++)
    {
      Serial.print(lidar.Data[i].angle);
      Serial.print("deg\t|\t");
      Serial.print(lidar.Data[i].distance);
      Serial.println("mm");
    }
  }`

My problem is that I need the data continuously and save it in a background task to a buffer where I can get the newest measurements. They should be overwritten at least all 200ms that they are real time.
How can I solve this?

**Comment by KKest** [comment]
@jakobofner 
You can read the Data out of `stScanDataPoint_t DataBuffer[1500]`.  In your example `lidar.data` is alway empty becouse it´s the Buffer for the express scan.

If you need the Data fast, you should use express scan. It is faster and also more accurate.

- copy the Buffer after a scan and then use the Data.
- programm a cicular buffer 

Thats not part of this repo and it´s not planed to include this.
